### ISSUE TITLE
Pickle fails to import in Futhark 0.25.7

### ISSUE THREAD

**Issue by havaker** [diku-dk/pickle#3]
I followed the installation instructions from the README.md and got the following output while trying to import pickle from inside repl:
```shell
> futhark repl
┃╱╱ ┃╲    ┃   ┃╲  ┃╲   ╱
┃╱  ┃ ╲   ┃╲  ┃╲  ┃╱  ╱
┃   ┃  ╲  ┃╱  ┃   ┃╲  ╲
┃   ┃   ╲ ┃   ┃   ┃ ╲  ╲
Version 0.25.7.
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.

Run :help for a list of commands.
[0]> import "lib/github.com/diku-dk/pickle/pickle"
Error at lib/github.com/diku-dk/pickle/pickle.fut:152:44-49:
Cannot apply "split" to "(k * m)" (invalid type).
Expected: [n₃₉ + m₄₀]t₄₁
Actual:   i64
```

That's the version of Futhark I was using:

```shell
> futhark --version
Futhark 0.25.7
Copyright (C) DIKU, University of Copenhagen, released under the ISC license.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Pickle version:

```shell
> cat futhark.pkg
require {
  github.com/diku-dk/pickle 0.2.0 #a18fdc6cc7d2f6b2640d0f8c0b8233c2b6393a3d
}
```

**Comment by havaker** [comment]
This is probably due to `split` function signature change in 0.25.1:
0.24.3: https://github.com/diku-dk/futhark/blob/d4bc0f4492975707688d225498e740a8f2e8a857/prelude/array.fut#L51C1-L52C20
0.25.1: https://github.com/diku-dk/futhark/blob/731acb97f30b2c620b8c6b6279a59f825aa6de88/prelude/array.fut#L56-L57

**Comment by athas** [comment]
You are correct, and I have fixed it now. But instead of using `pickle`, it is in most cases more efficient to use the store/restore functions [exposed in the C API](https://futhark.readthedocs.io/en/latest/c-api.html#opaque-values).

**Comment by havaker** [comment]
That was fastt, thanks for the advice!
